# -*- coding: utf-8 -*-
"""Customer_Retention_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10k_9S41nw-EQEe53EMimCvab0EWGfaT4

# Customer Retention Analysis for a Canadian E-Commerce Retailer

## Business Problem

The company wants to understand customer purchasing behavior, identify customers at risk of churn, and improve customer lifetime value (CLV).

For this project, a churned customer is defined as a customer who has not made a purchase in the last 90 days relative to the latest transaction date.

## Objectives

- Calculate key business KPIs.
- Measure customer retention and churn.
- Identify high-value customers.
- Analyze revenue by province and category.
- Recommend strategies to improve customer retention.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Show all columns (prevents pandas from hiding columns)
pd.set_option("display.max_columns", None)

df=pd.read_csv("Basket_IQ.csv")

print(df.to_string())

df.head(10)

df.tail(10)

"""# Initial Data Exploration (EDA)

In this section, we explore the dataset structure, identify missing values, check for duplicates, and understand the data types before cleaning and analysis.
"""

df.shape

df.info()

df.describe()

df.columns

df.dtypes

#checking null values
df.isnull().sum()

# finding the duplicates
df.duplicated().sum()

"""No duplicate records were found in the dataset; therefore, no duplicate removal was required."""

df.isnull()

# checking null in columns again
df.isnull().sum()

"""## Handling Missing Customer IDs

The dataset contained 8,105 transactions with missing customer IDs.

Since the objective of this project is customer retention analysis, these records were removed because customer behavior cannot be tracked without a unique identifier.
"""

#removing customer ids which are null
df.dropna(subset=["CustomerID"], inplace=True)

df.isnull().sum()

df["InvoiceDate"]=pd.to_datetime(df["InvoiceDate"])
df["InvoiceDate"].dtype

df.columns = df.columns.str.strip()
df.head(5)

# Check bad quantities
df[df["Quantity"] <= 0].shape

"""4,810 transactions have zero or negative quantities.

"""

df[df["UnitPrice_CAD"] <= 0].shape

"""No products have invalid prices."""

# Create revenue
df["Revenue"] = df["Quantity"] * df["UnitPrice_CAD"]

# Create month
df["Month"] = df["InvoiceDate"].dt.month

df = df[df["Quantity"] > 0]
df[df["Quantity"] <= 0].shape

"""### Handling Invalid Quantities

The dataset contained 4,810 transactions with zero or negative quantities.

These records were removed because they likely represent returns, cancellations, or data-entry issues. Since the objective of this project is customer purchase behavior and retention analysis, only completed purchases with positive quantities were retained.

## Customer-Level Aggregation

Transactional data was aggregated to the customer level to understand purchasing behavior.

For each customer, we calculated:

- Total revenue generated
- Number of orders placed
- Total items purchased
- Most recent purchase date

This enables retention and churn analysis at the customer level.
"""

# calculating a summary table for all transaction per customer
customer_summary = (
    df.groupby("CustomerID")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Total_Orders=("InvoiceNo", "nunique"),
          Total_Items=("Quantity", "sum"),
          Last_Purchase=("InvoiceDate", "max")
      )
      .reset_index()
)

customer_summary.head()
customer_summary.shape

"""This means we have 4958 unique customers."""

customer_summary.head(5)

#finding latest transaction dates
latest_date = df["InvoiceDate"].max()

print(latest_date)

customer_summary["Days_Inactive"] = (
    latest_date - customer_summary["Last_Purchase"]
).dt.days

customer_summary.head()

customer_summary["Customer_Status"] = np.where(
    customer_summary["Days_Inactive"] <= 30,
    "Active",
    np.where(
        customer_summary["Days_Inactive"] <= 90,
        "At Risk",
        "Churned"
    )
)

# providing customer_status

customer_summary["Customer_Status"].value_counts()

"""# Key Business Metrics (KPIs)

This section summarizes the company's performance and customer retention metrics.
"""

# Total Revenue
total_revenue = df["Revenue"].sum()

print(total_revenue)

# Total Customers
total_customers = df["CustomerID"].nunique()

print(total_customers)

#Total Orders
total_orders = df["InvoiceNo"].nunique()

print(total_orders)

# finding average order value
aov = total_revenue / total_orders

print(aov)

# finding revenue per customer
revenue_per_customer = total_revenue / total_customers

print(revenue_per_customer)

# Churn Rate
churn_rate = (
    customer_summary["Customer_Status"]
    .eq("Churned")
    .mean()
    * 100
)

print(churn_rate)

customer_summary["Customer_Status"].value_counts()

"""# Customer Retention Analysis

Customers were classified into three groups:

- Active: Purchased within the last 30 days.
- At Risk: No purchase for 31–90 days.
- Churned: No purchase for more than 90 days.

The analysis shows that approximately 34% of customers have churned, indicating opportunities for targeted retention and win-back campaigns.

## Q1: Who are the highest-value customers?
"""

top_customers = (
    customer_summary
    .sort_values("Total_Revenue", ascending=False)
    .head(10)
)

top_customers

"""## Q2: Which provinces generate the highest revenue?"""

province_revenue = (
    df.groupby("Province")["Revenue"]
      .sum()
      .sort_values(ascending=False)
      .reset_index()
)

province_revenue.head(10)

"""## Q3: Which product categories drive the most revenue?"""

category_revenue = (
    df.groupby("Category")["Revenue"]
      .sum()
      .sort_values(ascending=False)
      .reset_index()
)

category_revenue

"""## Q4: How has revenue changed over time?"""

monthly_revenue = (
    df.groupby("Month")["Revenue"]
      .sum()
      .reset_index()
)

monthly_revenue.head()

"""# Data Visualizations"""

# customer status distribution

customer_summary["Customer_Status"].value_counts().plot(
    kind="bar"
)

plt.title("Customer Status Distribution")
plt.xlabel("Status")
plt.ylabel("Number of Customers")

plt.show()

#Monthly Revenue Trend

plt.figure(figsize=(8,5))

plt.plot(
    monthly_revenue["Month"].astype(str),
    monthly_revenue["Revenue"]
)

plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue (CAD)")



plt.show()

#Top 5 Provinces
top_provinces = province_revenue.head(5)

plt.figure(figsize=(10,5))

plt.bar(
    top_provinces["Province"],
    top_provinces["Revenue"]
)

plt.title("Top Provinces by Revenue")
plt.xlabel("Province")
plt.ylabel("Revenue (CAD)")

plt.xticks(rotation=45)

plt.show()

#Top Categories
plt.figure(figsize=(8,5))

plt.bar(
    category_revenue["Category"],
    category_revenue["Revenue"]
)

plt.title("Revenue by Product Category")
plt.xlabel("Category")
plt.ylabel("Revenue (CAD)")
plt.xticks(rotation=45)

plt.show()

#Top Customers
plt.figure(figsize=(8,5))

plt.bar(
    top_customers["CustomerID"].astype(str),
    top_customers["Total_Revenue"]
)

plt.title("Top 10 Customers by Revenue")
plt.xlabel("Customer ID")
plt.ylabel("Revenue (CAD)")

plt.xticks(rotation=45)

plt.show()

top_customers.head()

province_revenue.head()

category_revenue.head()

"""# Executive Summary

## Business Overview

This project analyzed customer purchasing behavior for a Canadian e-commerce retailer using transactional data.

Customers were categorized as Active, At Risk, or Churned based on a 90-day inactivity rule.

## Key Metrics

- Total Customers: 4,958
- Churn Rate: 34.35%
- Active Customers: 1,751
- At-Risk Customers: 1,504
- Churned Customers: 1,703

## Top Province

Ontario generated the highest revenue, contributing significantly more than other provinces.

## Top Product Category

Sports & Outdoors was the highest-performing category by revenue.

# Key Findings

### 1. Customer churn remains significant

Approximately 34% of customers have churned, suggesting opportunities for retention and re-engagement strategies.

### 2. Repeat customers generate substantial value

The highest-value customers placed nearly 40 orders each, demonstrating the importance of customer loyalty.

### 3. Ontario is the dominant market

Ontario generated over CAD 5.4 million in revenue, making it the company's strongest region.

### 4. Sports & Outdoors leads sales

Sports & Outdoors products generated the highest revenue, followed by Clothing & Apparel and Home & Kitchen.

### 5. A large at-risk segment exists

More than 1,500 customers have not purchased within the last 31–90 days and should be targeted before they churn.

# Business Recommendations

### Recommendation 1: Launch win-back campaigns

Target the 1,703 churned customers with personalized promotions and discount offers to encourage repeat purchases.

### Recommendation 2: Protect at-risk customers

Implement automated email campaigns for customers inactive for 31–90 days before they become fully churned.

### Recommendation 3: Strengthen loyalty programs

Reward high-value customers through VIP programs, exclusive discounts, and early access to new products.

### Recommendation 4: Prioritize Ontario, British Columbia, and Quebec

Allocate marketing resources toward provinces generating the highest revenue while exploring growth opportunities in smaller markets.

### Recommendation 5: Expand high-performing categories

Increase investment in Sports & Outdoors and Clothing & Apparel products to capitalize on strong customer demand.
"""